---
abstract: 'Package that imports MediaMosa asset information into your application'
author:
  - 'Nicolas Franck <nicolas.franck@ugent.be>'
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-MediaMosa
provides:
  Catmandu::Importer::MediaMosa:
    file: lib/Catmandu/Importer/MediaMosa.pm
    version: 0.279
  Catmandu::MediaMosa:
    file: lib/Catmandu/MediaMosa.pm
    version: 0.279
  Catmandu::MediaMosa::Items:
    file: lib/Catmandu/MediaMosa/Items.pm
    version: 0
  Catmandu::MediaMosa::Items::asset:
    file: lib/Catmandu/MediaMosa/Items/asset.pm
    version: 0
  Catmandu::MediaMosa::Items::asset_list:
    file: lib/Catmandu/MediaMosa/Items/asset_list.pm
    version: 0
  Catmandu::MediaMosa::Items::login:
    file: lib/Catmandu/MediaMosa/Items/login.pm
    version: 0
  Catmandu::MediaMosa::Items::mediafile:
    file: lib/Catmandu/MediaMosa/Items/mediafile.pm
    version: 0
  Catmandu::MediaMosa::Items::simple_list:
    file: lib/Catmandu/MediaMosa/Items/simple_list.pm
    version: 0
  Catmandu::MediaMosa::Items::status:
    file: lib/Catmandu/MediaMosa/Items/status.pm
    version: 0
  Catmandu::MediaMosa::Response:
    file: lib/Catmandu/MediaMosa/Response.pm
    version: 0
  Catmandu::MediaMosa::Response::Header:
    file: lib/Catmandu/MediaMosa/Response/Header.pm
    version: 0
  Catmandu::MediaMosa::Response::Items:
    file: lib/Catmandu/MediaMosa/Response/Items.pm
    version: 0
  Catmandu::MediaMosa::XPath::Helper:
    file: lib/Catmandu/MediaMosa/XPath/Helper.pm
    version: 0
requires:
  Carp: 0
  Catmandu: 0.06
  Data::UUID: 0
  Data::Util: 0
  Digest::SHA1: 0
  LWP::UserAgent: 0
  Moo: 0.009011
  URI::Escape: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  all: 0
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.279
